companies:
- tenant: nvidia
  wd: wd5
  site: NVIDIAExternalCareerSite
  name: NVIDIA
- tenant: 3m
  wd: wd1
  site: Search
  name: 3m
- tenant: aba
  wd: wd1
  site: ABA
  name: aba
- tenant: abcsupply
  wd: wd1
  site: ABCSupplyCareers
  name: abcsupply
- tenant: abcsupply
  wd: wd1
  site: ACMcareers
  name: abcsupply
- tenant: abcsupply
  wd: wd1
  site: MuleHideCareers
  name: abcsupply
- tenant: abglobal
  wd: wd1
  site: alliancebernsteincareers
  name: abglobal
- tenant: abglobal
  wd: wd1
  site: abcampuscareers
  name: abglobal
- tenant: academy
  wd: wd1
  site: Careers
  name: academy
- tenant: acehardware
  wd: wd1
  site: AHHS_External
  name: acehardware
- tenant: acehardware
  wd: wd1
  site: AIH_External
  name: acehardware
- tenant: acehardware
  wd: wd1
  site: EJDExternal
  name: acehardware
- tenant: acehardware
  wd: wd1
  site: External
  name: acehardware
- tenant: acrisure
  wd: wd1
  site: Acrisure
  name: acrisure
- tenant: acrt
  wd: wd1
  site: ACRT_Careers
  name: acrt
- tenant: adventisthealthcare
  wd: wd1
  site: AdventistHealthCareCareers
  name: adventisthealthcare
- tenant: advisorgroup
  wd: wd1
  site: Advisor_Career_Site
  name: advisorgroup
- tenant: aenetworks
  wd: wd1
  site: AE-Careers
  name: aenetworks
- tenant: aes
  wd: wd1
  site: AES_Andes
  name: aes
- tenant: aes
  wd: wd1
  site: AES_ANDES
  name: aes
- tenant: aes
  wd: wd1
  site: AES_ARGENTINA
  name: aes
- tenant: aes
  wd: wd1
  site: AES_ASA
  name: aes
- tenant: aes
  wd: wd1
  site: AES_CHILE
  name: aes
- tenant: aes
  wd: wd1
  site: aes_clean_energy
  name: aes
- tenant: aes
  wd: wd1
  site: AES_MCAC
  name: aes
- tenant: aes
  wd: wd1
  site: AES_Mexico
  name: aes
- tenant: aes
  wd: wd1
  site: AES_PANAMA
  name: aes
- tenant: aes
  wd: wd1
  site: AES_PUERTORICO
  name: aes
- tenant: aes
  wd: wd1
  site: AES_US
  name: aes
- tenant: aes
  wd: wd1
  site: AES_DominicanRepublic
  name: aes
- tenant: aig
  wd: wd1
  site: aig
  name: aig
- tenant: aig
  wd: wd1
  site: early_careers
  name: aig
- tenant: aig
  wd: wd1
  site: japan
  name: aig
- tenant: allianceground
  wd: wd1
  site: AGI_Careers
  name: allianceground
- tenant: alliantenergy
  wd: wd1
  site: alliant
  name: alliantenergy
- tenant: allisontransmission
  wd: wd1
  site: ATI-External
  name: allisontransmission
- tenant: allisontransmission
  wd: wd1
  site: WDC-External
  name: allisontransmission
- tenant: altamed
  wd: wd1
  site: Careers
  name: altamed
- tenant: alterra
  wd: wd1
  site: AlterraMountainCompany
  name: alterra
- tenant: alterra
  wd: wd1
  site: BigBearMountainResort
  name: alterra
- tenant: alterra
  wd: wd1
  site: BlueMountainResort
  name: alterra
- tenant: alterra
  wd: wd1
  site: CMHHeli-Skiing
  name: alterra
- tenant: alterra
  wd: wd1
  site: DeerValleyResort
  name: alterra
- tenant: alterra
  wd: wd1
  site: CrystalMountain
  name: alterra
- tenant: alterra
  wd: wd1
  site: JuneMountain
  name: alterra
- tenant: alterra
  wd: wd1
  site: MammothMountain
  name: alterra
- tenant: alterra
  wd: wd1
  site: PalisadesTahoe
  name: alterra
- tenant: alterra
  wd: wd1
  site: Schweitzer
  name: alterra
- tenant: alterra
  wd: wd1
  site: SkiButlers
  name: alterra
- tenant: alterra
  wd: wd1
  site: SolitudeMountainResort
  name: alterra
- tenant: alterra
  wd: wd1
  site: SugarbushResort
  name: alterra
- tenant: alterra
  wd: wd1
  site: WinterParkResort
  name: alterra
- tenant: alterra
  wd: wd1
  site: SnowshoeMountain
  name: alterra
- tenant: alterra
  wd: wd1
  site: SteamboatSkiResort
  name: alterra
- tenant: alterra
  wd: wd1
  site: StrattonMountain
  name: alterra
- tenant: alwayscompassionate
  wd: wd1
  site: ACHomeCare
  name: alwayscompassionate
- tenant: amat
  wd: wd1
  site: External
  name: amat
- tenant: ambgroup
  wd: wd1
  site: AMB_FF
  name: ambgroup
- tenant: ambgroup
  wd: wd1
  site: AMBSE
  name: ambgroup
- tenant: ambgroup
  wd: wd1
  site: Appl_Only_Site
  name: ambgroup
- tenant: american
  wd: wd1
  site: AU
  name: american
- tenant: americanredcross
  wd: wd1
  site: American_Red_Cross_Careers
  name: americanredcross
- tenant: amfam
  wd: wd1
  site: Agent-Staff
  name: amfam
- tenant: amfam
  wd: wd1
  site: Agent-Staff-Private
  name: amfam
- tenant: amgen
  wd: wd1
  site: Careers
  name: amgen
- tenant: amlrightsource
  wd: wd1
  site: amlrightsource
  name: amlrightsource
- tenant: amn
  wd: wd1
  site: AMN_Careers
  name: amn
- tenant: amn
  wd: wd1
  site: AMN_Opportunities
  name: amn
- tenant: analogdevices
  wd: wd1
  site: External
  name: analogdevices
- tenant: salesforce
  wd: wd12
  site: External_Career_Site
  name: salesforce
- tenant: adobe
  wd: wd5
  site: external_experienced
  name: adobe
- tenant: workday
  wd: wd5
  site: Workday
  name: workday
- tenant: crowdstrike
  wd: wd5
  site: crowdstrikecareers
  name: crowdstrike
- tenant: intel
  wd: wd1
  site: External
  name: intel
- tenant: broadcom
  wd: wd1
  site: External_Career
  name: broadcom
- tenant: micron
  wd: wd1
  site: External
  name: micron
- tenant: kla
  wd: wd1
  site: Search
  name: kla
- tenant: marvell
  wd: wd1
  site: MarvellCareers
  name: marvell
- tenant: mastercard
  wd: wd1
  site: Campus
  name: mastercard
- tenant: gilead
  wd: wd1
  site: gileadcareers
  name: gilead
- tenant: boeing
  wd: wd1
  site: EXTERNAL_CAREERS
  name: boeing
- tenant: acehardware
  wd: wd1
  site: ahhs_external
  name: acehardware
- tenant: abglobal
  wd: wd1
  site: privatealliancebernsteincareers
  name: abglobal
- tenant: 3m
  wd: wd1
  site: search
  name: 3m
- tenant: aampower
  wd: wd1
  site: AAM-Career-Site
  name: aampower
