companies:
- slug: squarespace
  name: Squarespace
- slug: mozilla
  name: Mozilla
- slug: thumbtack
  name: Thumbtack
- slug: anduril
  name: Anduril Industries
- slug: verkada
  name: Verkada
- slug: nuro
  name: Nuro
- slug: waymo
  name: Waymo
- slug: cruise
  name: Cruise
- slug: aurora
  name: Aurora Innovation
- slug: zoox
  name: Zoox
- slug: anchorage
  name: Anchorage Digital
- slug: chainalysis
  name: Chainalysis
- slug: duolingo
  name: Duolingo
