companies:
- slug: netguru
  name: netguru
- slug: altom-transport
  name: Altom Transport
  aliases:
  - altom-transport
- slug: al-warren-oil-company-inc
  name: Al Warren Oil Company
  aliases:
  - al-warren-oil-company-inc
- slug: connectprep
  name: connectprep
- slug: coldquanta
  name: Infleqtion
  aliases:
  - coldquanta
- slug: onlogic-inc
  name: OnLogic
  aliases:
  - onlogic-inc
- slug: thorlabs
  name: thorlabs
- slug: datavisor-jobs
  name: DataVisor
  aliases:
  - datavisor-jobs
- slug: valsoft-corp
  name: Valsoft Corporation
  aliases:
  - valsoft-corp
- slug: terabase-energy
  name: Terabase
  aliases:
  - terabase-energy
- slug: enfos-inc
  name: ENFOS
  aliases:
  - enfos-inc
- slug: ascendis-pharma
  name: Ascendis Pharma
  aliases:
  - ascendis-pharma
- slug: quadric-dot-i-o-inc
  name: Quadric
  aliases:
  - quadric-dot-i-o-inc
- slug: tokamak-energy
  name: Tokamak Energy
  aliases:
  - tokamak-energy
- slug: tmeic-corporation-americas
  name: TMEIC Corporation Americas
  aliases:
  - tmeic-corporation-americas
- slug: eluvio
  name: eluvio
- slug: double-eleven
  name: Double Eleven
  aliases:
  - double-eleven
- slug: belmond-uk-ltd
  name: Belmond
  aliases:
  - belmond-uk-ltd
- slug: pony-dot-ai
  name: pony.ai
  aliases:
  - pony-dot-ai
- slug: ecareers
  name: e-Careers
  aliases:
  - ecareers
- slug: premium-merchant-funding-3
  name: Premium Merchant Funding
  aliases:
  - premium-merchant-funding-3
- slug: luminance-1
  name: Luminance
  aliases:
  - luminance-1
- slug: healthcorpsorg
  name: HealthCorps
  aliases:
  - healthcorpsorg
- slug: tarte-inc
  name: tarte cosmetics
  aliases:
  - tarte-inc
- slug: capula-investment-management-ltd
  name: Capula
  aliases:
  - capula-investment-management-ltd
- slug: flexion-robotics
  name: Flexion Robotics
  aliases:
  - flexion-robotics
- slug: hyperlight
  name: hyperlight
- slug: wallstreetquants
  name: wallstreetquants
- slug: skygig
  name: skygig
- slug: oceancomm
  name: oceancomm
- slug: q5-partners
  name: Q5
  aliases:
  - q5-partners
- slug: responsiveads-inc
  name: ResponsiveAds
  aliases:
  - responsiveads-inc
- slug: thingtrax
  name: thingtrax
- slug: generation-west-virginia-1
  name: Generation West Virginia
  aliases:
  - generation-west-virginia-1
- slug: cmic
  name: cmic
- slug: scitec
  name: scitec
- slug: dayshape
  name: dayshape
- slug: praytell
  name: praytell
- slug: elevate-semiconductor
  name: Elevate Semiconductor
  aliases:
  - elevate-semiconductor
- slug: rystad-energy
  name: Rystad Energy
  aliases:
  - rystad-energy
- slug: somerce
  name: somerce
- slug: twgai
  name: TWG Global
  aliases:
  - twgai
- slug: arena-investors-lp
  name: Arena Investors I Quaestor Advisors
  aliases:
  - arena-investors-lp
- slug: red-rabbit-robotics
  name: Red Rabbit Robotics
  aliases:
  - red-rabbit-robotics
- slug: luxium-solutions-llc
  name: Luxium Solutions
  aliases:
  - luxium-solutions-llc
- slug: sorting-robotics
  name: Sorting Robotics
  aliases:
  - sorting-robotics
- slug: kihomac
  name: kihomac
- slug: perryhomes
  name: Perry Homes
  aliases:
  - perryhomes
- slug: coretek-services
  name: Coretek Services
  aliases:
  - coretek-services
- slug: syntiant
  name: syntiant
- slug: zaber
  name: Zaber Technologies
  aliases:
  - zaber
- slug: fasanara
  name: fasanara
- slug: raveaerospace
  name: RAVE Aerospace
  aliases:
  - raveaerospace
- slug: javelin-global-commodities
  name: Javelin Global Commodities
  aliases:
  - javelin-global-commodities
- slug: cogna
  name: cogna
- slug: cadillacf1team
  name: Cadillac Formula 1 Team
  aliases:
  - cadillacf1team
- slug: grayce
  name: grayce
- slug: qodeworld
  name: qode.world
  aliases:
  - qodeworld
- slug: joinblink
  name: Blink
  aliases:
  - joinblink
- slug: twocircles
  name: Two Circles
  aliases:
  - twocircles
- slug: rokt
  name: rokt
- slug: optitrack
  name: optitrack
- slug: innovaccer-analytics
  name: Innovaccer
  aliases:
  - innovaccer-analytics
- slug: softheon
  name: softheon
- slug: optisigns-inc
  name: OptiSigns
  aliases:
  - optisigns-inc
- slug: trexquant
  name: trexquant
- slug: sigmadefense
  name: Sigma Defense
  aliases:
  - sigmadefense
- slug: charlotte-tilbury
  name: Charlotte Tilbury
  aliases:
  - charlotte-tilbury
- slug: starling-bank
  name: Starling Bank
  aliases:
  - starling-bank
- slug: tickpick
  name: tickpick
- slug: leap-legal-software
  name: LEAP Legal Software
  aliases:
  - leap-legal-software
- slug: oxford-quantum-circuits-8
  name: Oxford Quantum Circuits
  aliases:
  - oxford-quantum-circuits-8
- slug: texas-sports-academy-main
  name: Texas Sports Academy
  aliases:
  - texas-sports-academy-main
- slug: genetec-inc
  name: Genetec
  aliases:
  - genetec-inc
- slug: saalex
  name: saalex
- slug: civica-uk-ltd-1
  name: Civica
  aliases:
  - civica-uk-ltd-1
- slug: avalore
  name: avalore
- slug: indra-uk
  name: Indra Group UK & Ireland
  aliases:
  - indra-uk
- slug: alphax
  name: AlphaHire
  aliases:
  - alphax
- slug: interimage
  name: interimage
- slug: sword-group
  name: Sword Group
  aliases:
  - sword-group
- slug: msr-fsr
  name: msr-fsr
- slug: tp-link-usa-corp
  name: TP-Link Systems
  aliases:
  - tp-link-usa-corp
- slug: new-flyer
  name: New Flyer
  aliases:
  - new-flyer
- slug: cloudfactory
  name: cloudfactory
- slug: mila-2
  name: Montreal Institute for Learning Algorithms
  aliases:
  - mila-2
- slug: kanbrick
  name: kanbrick
- slug: arondite
  name: arondite
- slug: homey
  name: homey
- slug: teguar-corporation
  name: Teguar
  aliases:
  - teguar-corporation
- slug: vanguard-ems-inc
  name: Vanguard EMS
  aliases:
  - vanguard-ems-inc
- slug: christie-lites-3
  name: Christie
  aliases:
  - christie-lites-3
- slug: zaizi
  name: zaizi
- slug: avk-seg-uk-ltd
  name: AVK
  aliases:
  - avk-seg-uk-ltd
- slug: flexcompute
  name: flexcompute
- slug: fuse-integration
  name: Fuse Integration
  aliases:
  - fuse-integration
- slug: slip-robotics
  name: Slip Robotics
  aliases:
  - slip-robotics
- slug: fifty-five
  name: fifty-five
- slug: ubds
  name: UBDS Group
  aliases:
  - ubds
- slug: amax-1
  name: AMAX
  aliases:
  - amax-1
- slug: we-are-social-1
  name: We Are Social
  aliases:
  - we-are-social-1
- slug: dcthomson
  name: DC Thomson
  aliases:
  - dcthomson
- slug: arch-aerial-llc
  name: Arch Aerial
  aliases:
  - arch-aerial-llc
- slug: teserac-inc
  name: Teserac
  aliases:
  - teserac-inc
- slug: mustard-systems
  name: Mustard Systems
  aliases:
  - mustard-systems
- slug: the-anywhere-company
  name: The Anywhere
  aliases:
  - the-anywhere-company
- slug: eagle-seven
  name: Eagle Seven
  aliases:
  - eagle-seven
- slug: esgusa
  name: ESG - USA
  aliases:
  - esgusa
- slug: longshot-systems-ltd
  name: Longshot Systems
  aliases:
  - longshot-systems-ltd
- slug: cwill-us
  name: CWILL
  aliases:
  - cwill-us
- slug: lovey
  name: lovey
- slug: onyx-capital-group
  name: Onyx Capital Group
  aliases:
  - onyx-capital-group
- slug: murphy-research
  name: Murphy Research
  aliases:
  - murphy-research
- slug: lovingly
  name: lovingly
- slug: szns
  name: SZNS Solutions
  aliases:
  - szns
- slug: viewline-ventures
  name: Viewline Ventures
  aliases:
  - viewline-ventures
- slug: ripjar
  name: ripjar
- slug: alexander-dennis
  name: Alexander Dennis
  aliases:
  - alexander-dennis
- slug: vectoratomic
  name: Vector Atomic
  aliases:
  - vectoratomic
- slug: matternet
  name: matternet
- slug: planetart
  name: planetart
- slug: paxton-access
  name: Paxton Access
  aliases:
  - paxton-access
- slug: validus-risk-management
  name: Validus Risk Management
  aliases:
  - validus-risk-management
- slug: go-media
  name: GO Media
  aliases:
  - go-media
- slug: vortexa
  name: vortexa
- slug: seeq
  name: seeq
- slug: focus-group
  name: Focus Group
  aliases:
  - focus-group
- slug: willis-aviation
  name: Willis Aviation
  aliases:
  - willis-aviation
- slug: digitalmediaservices
  name: DMS
  aliases:
  - digitalmediaservices
- slug: blacklinesafety
  name: Blackline Safety
  aliases:
  - blacklinesafety
- slug: bestex-research
  name: BestEx Research
  aliases:
  - bestex-research
- slug: solirius-consulting-1
  name: Solirius Reply
  aliases:
  - solirius-consulting-1
- slug: employee-owned-holdings-inc
  name: Employee Owned Holdings
  aliases:
  - employee-owned-holdings-inc
- slug: rebellion
  name: rebellion
- slug: bci-brands
  name: BCI Brands
  aliases:
  - bci-brands
- slug: rovex-technologies-corporation
  name: Rovex Technologies
  aliases:
  - rovex-technologies-corporation
- slug: aetos-systems-inc
  name: Aetos Systems
  aliases:
  - aetos-systems-inc
- slug: currier-plastics
  name: Currier Plastics
  aliases:
  - currier-plastics
